### ISSUE TITLE
Использовать notifyItemInserted

### ISSUE THREAD

**Issue by govorovsky** [Igormamman/dz#2]
https://github.com/Igormamman/dz/blob/7dc50dc4ad409428a2cdbafe9a030b22b51f4665/app/src/main/java/com/example/dz/first_frag.java#L126

для одиночных вставок нужно использовать соответствующие методы

**Comment by Igormamman** [comment]
void setData(int size) {
            for (int i = 1; i <= size; i++) {
                number1.add(i);
                notifyItemInserted(i);
            }
        }
